//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par RetroCode-Exception.rc
//
#define IDS_REPARSE_ERROR_OUTOFMEMORY   1000
#define IDS_REPARSE_ERROR_BRACE_EXPECTED 1001
#define IDS_REPARSE_ERROR_PAREN_EXPECTED 1002
#define IDS_REPARSE_ERROR_BRACKET_EXPECTED 1003
#define IDS_REPARSE_ERROR_UNEXPECTED    1004
#define IDS_REPARSE_ERROR_EMPTY_RANGE   1005
#define IDS_REPARSE_ERROR_INVALID_GROUP 1006
#define IDS_REPARSE_ERROR_INVALID_RANGE 1007
#define IDS_REPARSE_ERROR_EMPTY_REPEATOP 1008
#define IDS_REPARSE_ERROR_INVALID_INPUT 1009
#define IDS_REPARSE_ERROR_OK            1010
#define IDS_MMIOERR_FILENOTFOUND        1011
#define IDS_MMIOERR_CANNOTOPEN          1012
#define IDS_MMIOERR_CANNOTCLOSE         1013
#define IDS_MMIOERR_ACCESSDENIED        1014
#define IDS_MMIOERR_INVALIDFILE         1015
#define IDS_MMIOERR_NETWORKERROR        1016
#define IDS_MMIOERR_PATHNOTFOUND        1017
#define IDS_MMIOERR_SHARINGVIOLATION    1018
#define IDS_MMIOERR_TOOMANYOPENFILES    1019
#define IDS_MMIOERR_CHUNKNOTFOUND       1020
#define IDS_MMIOERR_CANNOTSEEK          1021
#define IDS_MMIOERR_CANNOTWRITE         1022
#define IDS_MMIOERR_CANNOTEXPAND        1023
#define IDS_MMIOERR_CANNOTREAD          1024
#define IDS_MMIOERR_OUTOFMEMORY         1025
#define IDS_MMIOERR_UNBUFFERED          1026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
