name: MSBuild

on:

  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:
  
    name: ${{ matrix.os }} ${{ matrix.platform }} ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        platform: [x86, x64]
        configuration: ['Debug', 'Release']

    env: 
    
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Run Build and Code Analysis
        run: msbuild VisualC/RetroCode.sln -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}  

      - name: Run Unit Tests
        uses: rusty-bender/vstest-action@main
        with:
          testAssembly: VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/RetroCode-Math.Test.dll      
