name: MSBuild

on:

  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:
  
    runs-on: windows-2022

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup VSTest to PATH
        uses: darenm/Setup-VSTest@v1.2

      - name: Run MSBuild Debug
        run: msbuild build/RetroCode/RetroCore.sln -property:Configuration=Debug -property:Platform=x64
            
      - name: Run MSBuild Release
        run: msbuild build/RetroCode/RetroCore.sln -property:Configuration=Release -property:Platform=x64

      - name: Run Debug Tests (for memory leaks)
        run: vstest.console.exe build/RetroCode/x64/Debug/RetroCore.Test.dll

      - name: Run Release Tests (client version)
        run: vstest.console.exe build/RetroCode/x64/Release/RetroCore.Test.dll
      
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1.2.0

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RetroCode-artifact
          path: |
              include
              build/RetroCode/x64/Release/RetroCore.dll
              build/RetroCode/x64/Release/RetroCore.lib
              build/RetroCode/x64/Debug/RetroCore.dll
              build/RetroCode/x64/Debug/RetroCore.pdb
              build/RetroCode/x64/Debug/RetroCore.lib
