name: MSBuild

on:

  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:
  
    name: ${{ matrix.os }} ${{ matrix.platform }} ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        platform: [x86, x64]
        configuration: ['Debug', 'Release']

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Run MSBuild
        run: msbuild VisualC/RetroCode.sln -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}  

      - name: Run Tests
        uses: microsoft-approved-actions/vstest@master
        with:
          testAssembly: RetroCode-*.Test.dll
          searchFolder: VisualC/${{ matrix.platform }}/${{ matrix.configuration }}
          runInParallel: true