name: MSBuild

on:

  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:  
    name: ${{ matrix.os }} ${{ matrix.platform }} ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
          os: [windows-2022]
          platform: [x86, x64]
          configuration: [Debug, Release]

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup VSTest to PATH
        uses: darenm/Setup-VSTest@v1.2

      - name: Run MSBuild
        run: msbuild build/RetroCode/RetroCode.sln -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Run Tests
        run: vstest.console.exe build/RetroCode/${{ matrix.platform }}/${{ matrix.configuration }}/RetroCore.Test.dll
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RetroCode-${{ matrix.os }}-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
              build/RetroCode/${{ matrix.platform }}/${{ matrix.configuration }}/RetroCore.dll
              build/RetroCode/${{ matrix.platform }}/${{ matrix.configuration }}/RetroCore.lib
